version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_USER: crypto_quant
      POSTGRES_PASSWORD: ${DB_PASSWORD:-crypto_quant_2024}
      POSTGRES_DB: crypto_quant
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crypto_quant -d crypto_quant"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - crypto_quant_net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - crypto_quant_net

  app:
    build: .
    depends_on:
      timescaledb:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://crypto_quant:${DB_PASSWORD:-crypto_quant_2024}@timescaledb:5432/crypto_quant
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=${ENVIRONMENT:-development}
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    networks:
      - crypto_quant_net
    restart: unless-stopped

volumes:
  timescale_data:
  redis_data:

networks:
  crypto_quant_net:
    driver: bridge