version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: crypto_quant_test
    ports:
      - "5433:5432"
    volumes:
      - timescale_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d crypto_quant_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  timescale_test_data: